<a href="https://colab.research.google.com/github/buburayam112/221230029-PengantarML/blob/main/praktikum_4_tensor__pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np


In [2]:
''' Operasi Dasar pada Jaringan Saraf (Versi Modifikasi)'''
import torch

# Simulasi data input: 40 sampel, 8 fitur
batch, fitur = 40, 8
data_input = torch.randn(batch, fitur) * 1.5
bobot = torch.randn(fitur, 1)
bias = torch.randn(1)

# Layer Linear Manual (y = XW + b) ===
def lapisan_linear(X, W, b):
    hasil = X @ W + b
    return hasil

keluaran_linear = lapisan_linear(data_input, bobot, bias)

# Fungsi Aktivasi ReLU ===
def aktivasi_relu(tensor):
    return torch.clamp(tensor, min=0.0)  # cara lain untuk ReLU

aktif = aktivasi_relu(keluaran_linear)

#  Normalisasi Batch Sederhana ===
def normalisasi_batch(data, eps=1e-6):
    mean = data.mean(dim=0, keepdim=True)
    std = data.std(dim=0, keepdim=True)
    hasil = (data - mean) / (std + eps)
    return hasil

data_norm = normalisasi_batch(data_input)

#  One-Hot Encoding Manual ===
def one_hot_encode(label_tensor, kelas):
    n = label_tensor.size(0)
    hasil = torch.zeros(n, kelas)
    hasil[torch.arange(n), label_tensor] = 1
    return hasil

label = torch.randint(0, 4, (12,))  # 4 kelas
encoded = one_hot_encode(label, 4)

print("=== INFORMASI OPERASI NEURAL NETWORK ===")
print("Input shape:", data_input.shape)
print("Weights shape:", bobot.shape)
print("Bias shape:", bias.shape)
print("Output shape:", keluaran_linear.shape)
print("Activated shape:", aktif.shape)
print("Normalized shape:", data_norm.shape)
print("Labels:", label)
print("One-hot shape:", encoded.shape)
print("One-hot encoded:\n", encoded)

#  IMPLEMENTASI PERKALIAN MATRIKS MANUAL ===
def perkalian_matriks_manual(A, B):
    """
    Perkalian matriks dari prinsip dasar
    """
    baris_A, kolom_A = A.shape
    baris_B, kolom_B = B.shape

    if kolom_A != baris_B:
        raise ValueError("Dimensi matriks tidak cocok")

    hasil = torch.zeros(baris_A, kolom_B)
    for i in range(baris_A):
        for j in range(kolom_B):
            hasil[i, j] = torch.sum(A[i, :] * B[:, j])
    return hasil

# Uji coba dengan matriks 3x3
M1 = torch.tensor([[2, 4, 1], [0, 3, 5], [1, 2, 2]], dtype=torch.float32)
M2 = torch.tensor([[3, 1, 2], [4, 5, 6], [7, 8, 9]], dtype=torch.float32)
hasil_manual = perkalian_matriks_manual(M1, M2)
hasil_torch = torch.matmul(M1, M2)

print("\n=== UJI PERKALIAN MATRIKS ===")
print("Matriks A:\n", M1)
print("Matriks B:\n", M2)
print("Manual Result:\n", hasil_manual)
print("Torch Result:\n", hasil_torch)
print("Apakah hasil sama:", torch.allclose(hasil_manual, hasil_torch))

# === BONUS: Simulasi Operasi Tensor Gambar ===
print("\n=== OPERASI TENSOR GAMBAR ===")
gambar_batch = torch.randn(2, 3, 28, 28)  # 2 gambar, 3 channel, 28x28 piksel
flattened = gambar_batch.reshape(2, 3, -1)
swapped = gambar_batch.permute(0, 2, 3, 1)

print("Original shape:", gambar_batch.shape)
print("Flattened shape:", flattened.shape)
print("Swapped shape:", swapped.shape)

# Operasi patching sederhana seperti convolution
def ekstrak_patch(tensor, kernel=5):
    patch = tensor.unfold(2, kernel, 2).unfold(3, kernel, 2)
    print("Patch shape:", patch.shape)
    return patch

patches = ekstrak_patch(gambar_batch)

# === VALIDASI ===
assert keluaran_linear.shape == (batch, 1)
assert torch.all(aktif >= 0)
assert data_norm.shape == data_input.shape
assert encoded.shape == (12, 4)
assert torch.allclose(hasil_manual, hasil_torch)

print("\n✅ Semua pengujian berhasil! Kode berjalan dengan benar.")


=== INFORMASI OPERASI NEURAL NETWORK ===
Input shape: torch.Size([40, 8])
Weights shape: torch.Size([8, 1])
Bias shape: torch.Size([1])
Output shape: torch.Size([40, 1])
Activated shape: torch.Size([40, 1])
Normalized shape: torch.Size([40, 8])
Labels: tensor([3, 2, 2, 0, 1, 2, 0, 0, 1, 1, 2, 0])
One-hot shape: torch.Size([12, 4])
One-hot encoded:
 tensor([[0., 0., 0., 1.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])

=== UJI PERKALIAN MATRIKS ===
Matriks A:
 tensor([[2., 4., 1.],
        [0., 3., 5.],
        [1., 2., 2.]])
Matriks B:
 tensor([[3., 1., 2.],
        [4., 5., 6.],
        [7., 8., 9.]])
Manual Result:
 tensor([[29., 30., 37.],
        [47., 55., 63.],
        [25., 27., 32.]])
Torch Result:
 tensor([[29., 30., 37.],
        [47., 5